import * as fs from 'fs';
import * as path from 'path';
import { PromiseTokens, hasToken } from './types/index.js';
import { spawnWorker } from './spawn-worker.js';
import { loadConfig, getExtensionRoot } from './services/config.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export const WORKER_ROLES = ['requirements', 'codebase', 'risk-scope'] as const;
export type RoleId = typeof WORKER_ROLES[number];

export interface RefinementWorkerResult {
  role: RoleId;
  cycle: number;
  success: boolean;
  output_path: string;
}

export interface RefinementManifest {
  cycles_completed: number;
  cycles_requested: number;
  early_termination: boolean;
  workers: RefinementWorkerResult[];
  portal_context: boolean;
}

// ---------------------------------------------------------------------------
// Prompt Building
// ---------------------------------------------------------------------------

const ROLE_LABELS: Record<RoleId, string> = {
  requirements: 'Requirements Analyst',
  codebase: 'Codebase Context Analyst',
  'risk-scope': 'Risk & Scope Auditor',
};

export function buildRefinementPrompt(
  roleId: RoleId,
  prdContent: string,
  outputFile: string,
  workingDir: string,
  cycle: number,
  previousAnalyses?: Map<RoleId, string>,
  portalDir?: string,
): string {
  const persona = `You are a focused analyst. Be specific, actionable, and evidence-backed.
CRITICAL RULE: You MUST output a text explanation before every single tool call.`;

  const roleInstructions: Record<RoleId, string> = {
    requirements: `## Your Role: Requirements Analyst

Analyze the PRD EXCLUSIVELY for requirements completeness:
1. **Critical User Journeys (CUJs)**: Are all major user flows documented? Step-by-step enough for engineering?
2. **Functional Requirements Table**: Are P0/P1/P2 requirements complete? Missing use cases, alternate flows, error scenarios?
3. **Acceptance Criteria**: Can each requirement be tested? Success and failure states defined?
4. **Edge Cases & Boundary Conditions**: Missing empty states, error states, race conditions, limits?
5. **User Stories**: Specific enough to code against, or vague aspirations?

DO NOT analyze risks, scope, technical architecture, or codebase.`,

    codebase: `## Your Role: Codebase Context Analyst

Analyze alignment between the PRD and the actual codebase at: \`${workingDir}\`

1. **Research the codebase** — use Glob/Grep/Read to find relevant files. Map existing patterns.
2. **PRD Assumptions**: Does the PRD assume components that don't exist? Ignore existing patterns?
3. **Technical Constraints**: Existing APIs, data models, architectural decisions affecting this PRD?
4. **Integration Points**: What existing components will this feature touch?
5. **Missing Technical Context**: What decisions does the PRD leave unspecified?

Use file:line references for every codebase claim.`
      + (portalDir ? `

## Portal Artifacts

This PRD was generated by portal-gun from a donor codebase. Portal artifacts available:
- Pattern analysis: \`${portalDir}/pattern_analysis.md\`
- Target analysis: \`${portalDir}/target_analysis.md\`
- Donor source: \`${portalDir}/donor/\`

Read these artifacts to validate PRD claims against donor code and target analysis.` : ''),

    'risk-scope': `## Your Role: Risk & Scope Auditor

Analyze the PRD EXCLUSIVELY for risks, scope, and assumptions:
1. **Scope Clarity**: Is "In-scope" specific enough? Grade each item (vague/clear/precise).
2. **Non-Goals / Scope Creep**: Non-goals clearly stated? Scope creep hiding in vague requirements?
3. **Risk Completeness**: All major technical, product, operational risks identified?
4. **Mitigation Quality**: Concrete mitigations or hand-wavy "we'll monitor it"?
5. **Assumptions**: All key assumptions documented? Hidden assumptions that could blow up?
6. **External Dependencies**: APIs, third-party services, other teams under-specified?

DO NOT analyze feature completeness or codebase patterns.`,
  };

  let crossRefSection = '';
  if (cycle > 1 && previousAnalyses && previousAnalyses.size > 0) {
    crossRefSection = `\n## Previous Cycle Analyses (Cycle ${cycle - 1} — Cross-Reference These)

Your team already ran a previous analysis pass. You have access to ALL analysts' findings below.

**Your mission for this deeper pass:**
1. **Go DEEPER** on issues identified but under-explored — add specifics, evidence, examples
2. **CROSS-REFERENCE** findings from other analysts that affect your domain
3. **CHALLENGE** your own previous analysis — did you miss anything? Were severity ratings accurate?
4. **ELIMINATE DUPLICATES** — if another analyst covered something in your domain, acknowledge it
5. **RAISE NEW ISSUES** discovered only by seeing the full picture across all analyses

`;

    for (const [id, content] of previousAnalyses) {
      const label = ROLE_LABELS[id] || id;
      const isOwn = id === roleId;
      crossRefSection += `### ${label}'s Previous Findings${isOwn ? ' (YOUR OWN — improve on this)' : ''}:
\`\`\`markdown
${content}
\`\`\`

`;
    }
  }

  const cycleNote = cycle > 1
    ? `\n**THIS IS CYCLE ${cycle}** — you are deepening a previous analysis. Your output should be MORE SPECIFIC, MORE EVIDENCE-BACKED, and CROSS-REFERENCED with other analysts' findings.\n`
    : '';

  const outputInstructions = `## Your Output

Write ALL findings to this file: ${outputFile}
${cycleNote}
Use this EXACT structure:

\`\`\`markdown
# PRD Analysis: [Your Role Name]${cycle > 1 ? ` (Cycle ${cycle})` : ''}

**Date**: [Today's date]
**Analyst**: [Your Role Name]
**Cycle**: ${cycle}

## Executive Summary
[2-3 sentence overview of PRD quality in your domain. Be specific.]

## Critical Gaps (P0 — Must Fix)
- **[Gap Title]**: [Specific description with PRD section reference]. [Why critical.]

## Important Gaps (P1 — Should Fix)
- **[Gap Title]**: [Specific description]. [Impact if ignored.]

## Minor Issues (P2 — Nice to Fix)
- [Brief description]

## Specific Recommendations
[Concrete, actionable suggestions. For P0 gaps, provide example language.]${cycle > 1 ? `

## Cross-Reference Notes
[What you found by reading other analysts' work that affects your domain]` : ''}
\`\`\`

After writing the file, output: <promise>${PromiseTokens.ANALYSIS_DONE}</promise>
Then STOP IMMEDIATELY. Do not attempt to rewrite the PRD.`;

  return `${persona}

${roleInstructions[roleId]}
${crossRefSection}
---

## The PRD You Are Analyzing

\`\`\`markdown
${prdContent}
\`\`\`

---

${outputInstructions}`;
}

// ---------------------------------------------------------------------------
// Core Logic
// ---------------------------------------------------------------------------

export async function spawnRefinementTeam(
  sessionDir: string,
  prdPath: string,
  cycles?: number,
): Promise<RefinementManifest> {
  if (!fs.existsSync(sessionDir)) {
    throw new Error(`Session directory not found: ${sessionDir}`);
  }
  if (!fs.existsSync(prdPath)) {
    throw new Error(`PRD file not found: ${prdPath}`);
  }

  const config = loadConfig();
  const requestedCycles = cycles ?? config.defaults.refinement_cycles;
  const timeout = config.defaults.refinement_worker_timeout_seconds;
  const extensionRoot = getExtensionRoot();
  const workingDir = process.cwd();

  const refinementDir = path.join(sessionDir, 'refinement');
  fs.mkdirSync(refinementDir, { recursive: true });

  const prdContent = fs.readFileSync(prdPath, 'utf-8');

  const portalDir = path.join(sessionDir, 'portal');
  const hasPortal = fs.existsSync(portalDir);

  const allWorkerResults: RefinementWorkerResult[] = [];
  let cyclesCompleted = 0;
  let earlyTermination = false;

  for (let cycle = 1; cycle <= requestedCycles; cycle++) {
    // Load previous analyses for cross-reference (cycle 2+)
    let previousAnalyses: Map<RoleId, string> | undefined;
    if (cycle > 1) {
      previousAnalyses = new Map();
      for (const roleId of WORKER_ROLES) {
        const prevFile = path.join(refinementDir, `analysis_${roleId}.md`);
        if (fs.existsSync(prevFile)) {
          try {
            previousAnalyses.set(roleId, fs.readFileSync(prevFile, 'utf-8'));
          } catch { /* skip unreadable */ }
        }
      }
    }

    // Build prompts and spawn workers in parallel
    const workerPromises = WORKER_ROLES.map(async (roleId): Promise<RefinementWorkerResult> => {
      const outputFile = path.join(refinementDir, `analysis_${roleId}.md`);
      const prompt = buildRefinementPrompt(
        roleId,
        prdContent,
        outputFile,
        workingDir,
        cycle,
        previousAnalyses,
        hasPortal ? portalDir : undefined,
      );

      const logFile = path.join(refinementDir, `worker_${roleId}_c${cycle}.log`);

      try {
        const result = await spawnWorker({
          prompt,
          runtime: config.primary_cli,
          cwd: workingDir,
          logFile,
          timeout,
          ticketPath: refinementDir,
          extensionRoot,
        });

        const success = hasToken(result.stdout, PromiseTokens.ANALYSIS_DONE);
        const outputPath = `analysis_${roleId}_c${cycle}.md`;

        return { role: roleId, cycle, success, output_path: outputPath };
      } catch {
        return { role: roleId, cycle, success: false, output_path: `analysis_${roleId}_c${cycle}.md` };
      }
    });

    const cycleResults = await Promise.allSettled(workerPromises);
    const results: RefinementWorkerResult[] = cycleResults.map((r) =>
      r.status === 'fulfilled'
        ? r.value
        : { role: 'requirements' as RoleId, cycle, success: false, output_path: '' },
    );

    // Archive cycle results
    for (const roleId of WORKER_ROLES) {
      const canonical = path.join(refinementDir, `analysis_${roleId}.md`);
      const cycleArchive = path.join(refinementDir, `analysis_${roleId}_c${cycle}.md`);
      if (fs.existsSync(canonical)) {
        try { fs.copyFileSync(canonical, cycleArchive); } catch { /* best-effort */ }
      }
    }

    allWorkerResults.push(...results);
    cyclesCompleted = cycle;

    // Early termination if ALL workers failed
    if (results.every((r) => !r.success)) {
      earlyTermination = true;
      break;
    }
  }

  const manifest: RefinementManifest = {
    cycles_completed: cyclesCompleted,
    cycles_requested: requestedCycles,
    early_termination: earlyTermination,
    workers: allWorkerResults,
    portal_context: hasPortal,
  };

  // Atomic write manifest
  const manifestPath = path.join(sessionDir, 'refinement_manifest.json');
  const manifestTmp = `${manifestPath}.tmp.${process.pid}`;
  try {
    fs.writeFileSync(manifestTmp, JSON.stringify(manifest, null, 2));
    fs.renameSync(manifestTmp, manifestPath);
  } catch (err) {
    try { fs.unlinkSync(manifestTmp); } catch { /* cleanup */ }
    throw err;
  }

  return manifest;
}

// ---------------------------------------------------------------------------
// CLI Entry Point
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const sessionDir = args[0];
  const prdPath = args[1];

  if (!sessionDir || !prdPath) {
    console.error('Usage: node spawn-refinement-team.js <session-dir> <prd-path> [--cycles N]');
    process.exit(1);
  }

  const cyclesIndex = args.indexOf('--cycles');
  let cycles: number | undefined;
  if (cyclesIndex !== -1) {
    const raw = parseInt(args[cyclesIndex + 1], 10);
    if (isNaN(raw) || raw < 1) {
      console.error('--cycles requires a positive integer');
      process.exit(1);
    }
    cycles = raw;
  }

  const manifest = await spawnRefinementTeam(sessionDir, prdPath, cycles);

  console.log(JSON.stringify(manifest, null, 2));

  if (manifest.early_termination) {
    process.exit(1);
  }
}

if (process.argv[1] && path.basename(process.argv[1]) === 'spawn-refinement-team.js') {
  main().catch((err) => {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(msg);
    process.exit(1);
  });
}
